# Generated by Django 4.2.9 on 2024-01-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='modifed_at',
            new_name='modified_at',
        ),
    ]
